table 'Credit card transactions - India - Simple'
	lineageTag: d52b072e-3f20-437e-81af-9a3a066caf95

	measure 'Count of Date YTD' =
			
			IF(
				ISFILTERED('Credit card transactions - India - Simple'[Date]),
				ERROR("Time intelligence quick measures can only be grouped or filtered by the Power BI-provided date hierarchy or primary date column."),
				TOTALYTD(
					COUNTA('Credit card transactions - India - Simple'[Date]),
					'Credit card transactions - India - Simple'[Date].[Date]
				)
			)
		formatString: 0
		lineageTag: d7e7901f-9495-4097-aea3-ec4d4fb53d02

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "YearToDate"
				}

	measure 'Amount MTD' =
			
			IF(
				ISFILTERED('Credit card transactions - India - Simple'[Date]),
				ERROR("Time intelligence quick measures can only be grouped or filtered by the Power BI-provided date hierarchy or primary date column."),
				TOTALMTD(
					SUM('Credit card transactions - India - Simple'[Amount]),
					'Credit card transactions - India - Simple'[Date].[Date]
				)
			)
		formatString: 0
		lineageTag: 0b7bfac3-99da-471d-9d62-52b76c642875

		extendedProperty MeasureTemplate =
				{
				  "version": 0,
				  "daxTemplateName": "MonthToDate"
				}

		changedProperty = FormatString

	column index
		dataType: int64
		formatString: 0
		lineageTag: 99bece86-2060-421f-b1d7-a98af4b2a76f
		summarizeBy: sum
		sourceColumn: index

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: e707ee79-243f-4f5c-b0f0-502537bcdc2d
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: d57c888b-41ca-4ac4-bac9-e80eed12ff5d
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 074a6c11-210f-46cb-a21e-b4af62c46597
			defaultHierarchy: LocalDateTable_c4e66e49-818c-45d5-8733-03e0951156e1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Card Type'
		dataType: string
		lineageTag: d4c112a8-802d-467a-a976-a795f79c1548
		summarizeBy: none
		sourceColumn: Card Type

		annotation SummarizationSetBy = Automatic

	column 'Exp Type'
		dataType: string
		lineageTag: 03fde515-7253-4186-8a63-594dc789ff23
		summarizeBy: none
		sourceColumn: Exp Type

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: e0278c74-6840-4324-9b94-2f6078a6f7b4
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column Amount
		dataType: int64
		formatString: 0
		lineageTag: b949383f-3ed9-4bf8-a2cf-f4df560c2f83
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

	partition 'Credit card transactions - India - Simple-7e4666d4-757d-444a-b2a1-a939920ea3c4' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Najwan\OneDrive\Desktop\Datasets\Credit card transactions - India - Simple.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"index", Int64.Type}, {"City", type text}, {"Date", type date}, {"Card Type", type text}, {"Exp Type", type text}, {"Gender", type text}, {"Amount", Int64.Type}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type",", India","",Replacer.ReplaceText,{"City"})
				in
				    #"Replaced Value"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

